"""increase stance column length

Revision ID: 97bebe0d4a5f
Revises: bfd0941c3f7b
Create Date: 2025-01-15 17:04:45.929973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '97bebe0d4a5f'
down_revision = 'bfd0941c3f7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stance_predictions', 'target_club',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('stance_predictions', 'stance',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stance_predictions', 'stance',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('stance_predictions', 'target_club',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###